language: cpp
compiler:
  - gcc
branches:
  only:
  - master

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - cmake
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
script:
  - mkdir build && cd build && cmake .. && make
