language:cpp
compiler:
  - gcc
branches:
  only:
  - master

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - cmake
      env:
         - MATRIX_EVAL="CC=gcc && CXX=g++"
 script:
   - mkdir build && cd build && cmake .. && make
