jobs:
  build:
    docker:
    - image: circleci/ruby:stretch
    steps:
    - checkout
    - run:
        name: Set up
        command: |
          sudo apt-get update
          sudo apt-get install cmake
          mkdir build
    - run: |
        cd ./build
        cmake ..
        make
workflows:
  version: 2
  workflow:
    jobs:
    - build
